version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /.github/actions/semantic-release
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /.github/actions/semantic-release
    schedule:
      interval: daily