name: 🚀 Release dns_exporter

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read # for checkout

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    name: Create Release
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
