name: 🚀 Release dns_exporter

on:
  push:
    branches:
      - main
      - "*.x"
  workflow_dispatch:

permissions:
  contents: read # for checkout

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          path: /app
      - name: Create Release
        uses: ./.github/actions/semantic-release/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
